requirements: fix python 2.7 install requiring setuptools<45
As described in [1], support for python 2.7 was removed in setuptools >= 45
and it must be pinned.

This commit fixes error like the following:

  ERROR: Package 'setuptools' requires a different Python: 2.7.17 not in '>=3.5'

See #478

[1] https://github.com/pypa/setuptools/blob/v46.1.3/.github/ISSUE_TEMPLATE/setuptools-warns-about-python-2-incompatibility.md