travis: Disable 3.7.0 because cmake wheel not available
Associated error was the following and also prevented the wheel from
being built from source:

```
[scikit-ci] Executing: pip install cmake
Collecting cmake
  Downloading https://files.pythonhosted.org/packages/46/ae/51c30e300f82ada43eaba14cb0157acb03c7c6894efd5129e52338cb41aa/cmake-3.11.0.tar.gz (30.8MB)
    [...]
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/pip-install-p19dp376/cmake/setup.py", line 6, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'
```